### ISSUE TITLE
PNG Images doesn't change color on dark mode

### ISSUE THREAD

**Issue by Famapohl** [originecode/aemi#1]
Hi, the problem is that when you have .png images with black text on the website, the text isn't visible on dark mode.

**Comment by originecode** [comment]
Hi @Famapohl 

Actually I do not plan to help with this. Why ? Because if we invert colours of a picture, all pictures won't be displayed as wanted. Later, I could be able to add a picture-per-picture invert tickbox in Gutenberg editor or in each media page. But it is not a good way to solve it. I think you have to use picture without text and add text in html / Gutenberg-block.

Hope I helped you.

Best Regards

**Comment by originecode** [comment]
Feature added in Version 2.0-beta5.

Closing this issue.

Best Regards
