### ISSUE TITLE
Navigation only in the same category

### ISSUE THREAD

**Issue by evelujska** [originecode/aemi#2]
Hey,

is it somehow possible to only navigate posts within one category? I have the problem that my posts are filtered very chaotically bc wordpress lists it automatically by the date of publication. Doesn't make sense though if it lists posts from other categories as next or previous 

Thanks :)

**Comment by originecode** [comment]
Hi @evelujska 

I will investigate on it. Check in WordPress Customizer then Aemi settings if Categories are enabled and maybe change how your post are reachable in WordPress Settings > Permalink.

I'll come back later with more informations.

Best Regards

**Comment by originecode** [comment]
Hi @evelujska 

Sorry to come back so late. I would let you know that I completely misunderstood what you said (My english is not this good). Now that I fully catch the meaning of your words I can tell you that what you're asking for is possible. Still remaining if this filter has to be applied to home or blog or every post listings.

Kind Regards

**Comment by evelujska** [comment]
Hey @originecode :) 

Thank your for investigating on it and helpIng me! So if I understand you right you are wondering if I want to apply it to home or the rest? Or is it still within your investigation? 

Because if you are asking me I would actually love to use it within the blog and each listing so that it's closed within itself but so far I think you understood what I am going for 😊

Regards, 
Evelin

**Comment by originecode** [comment]
Okay, It's exactly what I was wondering.
The good news is that this feature will be in Aemi 2.0 and probably in the next beta version.
Aemi 2.0 will be released within a month (2 months max)
Regards ;) 
Guillaume

**Comment by evelujska** [comment]
Amazing, waiting for it excited!

**Comment by originecode** [comment]
Hi @evelujska 

I'm glad to be able to tell you that the feature has been implemented in Version 2.0-beta9.

However, this feature may encounter some weird behaviours due to WordPress (e.g. Sticky Posts from a different category that what is shown may stay visible. I do not recommend to use Loop Filtering and Sticky Posts from a different category.)
Also, Loop Filtering can not be used alongside Adding Post Types to the Loop (a new feature I've just implemented in beta9) due to these annoying WordPress bugs.

Otherwise, it works well.

Hope you'll like it.

Regards
